// <auto-generated />
namespace ChildhoodMinistry.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenericRep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenericRep));
        
        string IMigrationMetadata.Id
        {
            get { return "201610150902541_GenericRep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
